---
title: "Week 1 Codes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
```

#### ---------------------------------------------------------------------------
### Supervised Learning: Simulation of "true" vs predicted Relationship


```{r}
# simulate data
x <- runif(n = 100, min = 20, max = 40)   # input/predictor

e <- rnorm(n = 100, mean = 0, sd = 10)  # error

a <- 3
b <- 0.87
fx <- a + (b * x)  # true function

y <- fx + e   # observed responses

toy_data <- data.frame(input = x, true_form = fx, response = y)   # create data frame to store values
```


```{r, fig.align='center', fig.width=7, fig.height=5}
# plot input and true function
ggplot(data = toy_data, aes(x = input, y = true_form)) + 
  geom_point() + labs(title = "True relationship without error", y = "f(x)", x = "x")

# plot input and observed response 
ggplot(data = toy_data, aes(x = input, y = response)) + 
  geom_point() + labs(title = "Observed relationship", y = "y", x = "x") 

# plot "true" model (red) and predicted model (blue)
ggplot(data = toy_data, aes(x = input, y = response)) + 
  geom_point() + 
  geom_abline(aes(intercept = a, slope = b, color = "true model")) +
  geom_smooth(method = "lm", se = FALSE, aes(color = "predicted model")) +
  scale_color_manual(values = c("true model" = "red", "predicted model" = "blue")) +
  theme(legend.title = element_blank()) +
  labs(title = "Simulation of `true` vs predicted relationship", y = "y", x = "x")
```


#### ---------------------------------------------------------------------------
### Supervised Learning: Comparing Two Models


```{r}
# simulate data
x <- runif(n = 100, min = 20, max = 40)   # input/predictor

e <- rnorm(n = 100, mean = 0, sd = 1)  # error

a <- 3
b <- 0.87
c <- 0.5
fx <- a + (b * sqrt(x)) + (c * sin(x))   # true function

y <- fx + e    # observed responses

toy_data <- data.frame(input = x, true_form = fx, response = y)   # create data frame to store values
```


```{r, fig.align='center', fig.width=7, fig.height=5}
# plot input and true function
ggplot(data = toy_data, aes(x = input, y = true_form)) + 
  geom_point() + labs(title = "True relationship without error", y = "f(x)", x = "x")

# plot input and observed response 
ggplot(data = toy_data, aes(x = input, y = response)) + 
  geom_point() + labs(title = "Observed relationship", y = "y", x = "x")

# plot linear model (red) and non-linear model (blue)
ggplot(data = toy_data, aes(x = input, y = response)) + 
  geom_point() +
  geom_function(fun = function(x) a+(b*sqrt(x))+(c*sin(x)), aes(color = "true model"), linewidth = 1.5) +
  geom_smooth(method = "lm", se = FALSE, aes(color = "linear model")) +
  geom_smooth(formula = y ~ sqrt(x) + sin(x), se = FALSE, aes(color = "non-linear model")) +
  scale_color_manual(values = c("true model" = "red", "linear model" = "blue", "non-linear model" = "green")) +
  theme(legend.title = element_blank()) +
  labs(title = "Comparing two models", y = "y", x = "x")
```


#### ---------------------------------------------------------------------------
### Understanding Bias-Variance Trade-off

#### Comparison of bias between two models

```{r}
# simulate data
x <- runif(n = 100, min = 20, max = 40)  # input/predictor 

e <- rnorm(n = 100, mean = 0, sd = 1)   # error

a <- 3
b <- 0.87
c <- 0.5
fx <- a + (b * sqrt(x)) + (c * sin(x))   # true function

y <- fx + e  # observed responses

toy_data <- data.frame(input = x, response = y)   # create data frame to store values
```


```{r, fig.align='center', fig.width=7, fig.height=5}
# compare the bias between two fits: linear (bold) and curved (dashed), true function is in black
ggplot(data = toy_data, aes(x = input, y = response)) + 
  geom_point() + 
  geom_function(fun = function(x) a+(b*sqrt(x))+(c*sin(x)), aes(color = "true model"), linewidth = 1) +
  geom_smooth(method = "lm", se = FALSE) + 
  geom_smooth(formula = y ~ sqrt(x) + sin(x), linetype = "dashed", se = FALSE) +
  scale_color_manual(values = c("true model" = "red")) +
  theme(legend.title = element_blank()) +
  labs(title = "Comparison of bias between two models", y = "y", x = "x")
```


#### Comparison of variance within each model

```{r}
set.seed(55)

# first training data
x1 <- runif(n = 100, min = 20, max = 40)
e1 <- rnorm(n = 100, mean = 0, sd = 0.5)
fx1 <- 3 + (0.87*sqrt(x1)) + (0.5*sin(x1))
y1 <- fx1 + e1

# second training data
x2 <- runif(n = 100, min = 20, max = 40)
e2 <- rnorm(n = 100, mean = 0, sd = 0.5)
fx2 <- 3 + (0.87*sqrt(x2)) + (0.5*sin(x2))
y2 <- fx2 + e2

# third training data
x3 <- runif(n = 100, min = 20, max = 40)
e3 <- rnorm(n = 100, mean = 0, sd = 0.5)
fx3 <- 3 + (0.87*sqrt(x3)) + (0.5*sin(x3))
y3 <- fx3 + e3

dat <- data.frame(x1 = x1, y1 = y1, x2 = x2, y2 = y2, x3 = x3, y3 = y3)
```


```{r, fig.align='center', fig.width=7, fig.height=5}
# comparison of variance within the linear fits from three different datasets (true function is in black)
ggplot(data = dat) + 
  geom_function(fun = function(x) 3+(0.87*sqrt(x))+(0.5*sin(x)), aes(color = "true model"), linewidth = 1) +
  geom_smooth(aes(x=x1, y=y1), method = "lm", se = FALSE) + 
  geom_smooth(aes(x=x2, y=y2), method = "lm", se = FALSE, linetype = "dashed") +
  geom_smooth(aes(x=x3, y=y3), method = "lm", se = FALSE, linetype = "dotted") +
  labs(x="x", y="y") +
  scale_color_manual(values = c("true model" = "red")) +
  theme(legend.title = element_blank()) +
  labs(title = "Comparison of variance within the linear fits", y = "y", x = "x")
```


```{r, fig.align='center', fig.width=7, fig.height=5}
# comparison of variance within the non-linear fits from three different datasets (true function is in black)
ggplot(data = dat) + 
  geom_function(fun = function(x) 3+(0.87*sqrt(x))+(0.5*sin(x)), aes(color = "true model"), linewidth = 1) +
  geom_smooth(aes(x=x1, y=y1), formula = y ~ sqrt(x) + sin(x), se = FALSE) +
  geom_smooth(aes(x=x2, y=y2), formula = y ~ sqrt(x) + sin(x), linetype = "dashed", se = FALSE) +
  geom_smooth(aes(x=x3, y=y3), formula = y ~ sqrt(x) + sin(x), linetype = "dotted", se = FALSE) +
  labs(x="x", y="y") +
  scale_color_manual(values = c("true model" = "red")) +
  theme(legend.title = element_blank()) +
  labs(title = "Comparison of variance within the non-linear fits", y = "y", x = "x")
```


#### ---------------------------------------------------------------------------

